# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

name: quant-met-dev
channels:
  - defaults
dependencies:
  - python=3.12.2
  - pytables=3.9.2
  - pip
  - pip:
    - poetry==1.8.2
