# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

name: quant-met-dev
channels:
  - conda-forge
  - defaults
  - edipack
dependencies:
  - python=3.12
  - pip
  - triqs
  - uv
  - edipack2=2.0.8
  - pip:
      - pre-commit
