name: Linting

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  test:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libomp-dev libeigen3-dev 

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install the project
        run: uv sync --group=lint

      - uses: extractions/setup-just@v4

      - name: Run test suite
        run: just lint
