# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

name: Publish python package

on:
  push:
    tags:
      - "*.*.*"

permissions:
  pull-requests: write

jobs:
  tests:
    uses: ./.github/workflows/integration_tests.yml
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
