name: Build and Publish Wheels

on:
  release:
    types: [published] # Triggers automatically when you create a GitHub release

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Tells git to fetch all tags and history

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0 # Uses isolated docker/VM contexts to build
        env:
          CIBW_BEFORE_ALL_LINUX: "apt install -y libeigen3-dev libomp-dev"
          CIBW_BEFORE_ALL_MACOS: "brew install eigen libomp"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for secure trusted publishing to PyPI
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1