# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

name: Unit tests, linting and type checking

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v3
      - name: Run test suite
        run: just test --without-slow-integration
      - name: Coveralls
        uses: coverallsapp/github-action@v2
