# SPDX-FileCopyrightText: 2024 Tjark Sievers
#
# SPDX-License-Identifier: MIT

name: Unit tests, linting and type checking

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Run test suite
        run: just test --without-slow-integration
      - name: Coveralls
        uses: coverallsapp/github-action@v2
